support sample/release-sample target for sample firmware release flow
git-svn-id: http://rd1-1/subversion/SI/Tools/hathor/trunk@120147 7a6c5977-b700-0410-9ebf-f0490b269a9c

diff --git a/bin/firmware_tag_create b/bin/firmware_tag_create
--- a/bin/firmware_tag_create
+++ b/bin/firmware_tag_create
@@ -2,35 +2,52 @@
 
 # $Id:$
 
+[ "$1" == "sample" ] && THIS_IS_SAMPLE_FIRMWARE="y"
+
 source $HATHOR/config/basic_config
 source $HATHOR/lib/libfirmwareinfo
 source $HATHOR/lib/libmessage
 
 DEVEL_SOURCE_FILE="devel_`echo $PRODUCTVER | sed -e 's/-[^-]*$//' -e 's/-/_/g'`"
 cd ${PRODUCTDIR}
-pushd build
+pushd build > /dev/null
 source $DEVEL_SOURCE_FILE
-popd
+popd > /dev/null
 
-# check if current project directory is clean
-info "Check if everything is committed to subversion..."
-WORKING_COPY_NOT_CLEAN=`svn st | grep -E "^M|^A|^D|^C|^\!"`
-if [ -n "$WORKING_COPY_NOT_CLEAN" ]; then
-	warn "Following files is modified:"
-	warn "$WORKING_COPY_NOT_CLEAN"
-	warn "Please commit all your code before proceeding!"
-	exit 1
-fi
+# skip directory check when releasing sample firmware
+if [ "$THIS_IS_SAMPLE_FIRMWARE" != "y" ] ; then
 
-WORKING_COPY_HAS_MISSING_FILE=`svn st | grep -E "^\?"`
-if [ -n "$WORKING_COPY_HAS_MISSING_FILE" ]; then
-	info "You might want to add these files to subversion first."
-	info "You could also use svn to ignore these files in working copy."
-	echo "$WORKING_COPY_HAS_MISSING_FILE"
-	read -p "Do you still want to continue? [y/N] " SKIP_MISSING_FILES
-	if [ "$SKIP_MISSING_FILES" != "y" ] && [ "$SKIP_MISSING_FILES" != "Y" ] ; then
+	# check if current project directory is clean
+	info "Check if everything is committed to subversion..."
+	WORKING_COPY_NOT_CLEAN=`svn st | grep -E "^M|^A|^D|^C|^\!"`
+	if [ -n "$WORKING_COPY_NOT_CLEAN" ]; then
+		warn "Following files is modified:"
+		warn "$WORKING_COPY_NOT_CLEAN"
+		warn "Please commit all your code before proceeding!"
 		exit 1
 	fi
+
+	WORKING_COPY_HAS_MISSING_FILE=`svn st | grep -E "^\?"`
+	if [ -n "$WORKING_COPY_HAS_MISSING_FILE" ]; then
+		info "You might want to add these files to subversion first."
+		info "You could also use svn to ignore these files in working copy."
+		echo "$WORKING_COPY_HAS_MISSING_FILE"
+		read -p "Do you still want to continue? [y/N] " SKIP_MISSING_FILES
+		if [ "$SKIP_MISSING_FILES" != "y" ] && [ "$SKIP_MISSING_FILES" != "Y" ] ; then
+			exit 1
+		fi
+	fi
+else
+	FIRMWARE_VERSION=$PRODUCTVER
+	hathor_get_firmware_type > /dev/null
+	if [ "$HATHOR_FIRMWARE_TYPE" != "Sample" ] ; then
+		warn "Your version number does not follow sample firmware rule ($PRODUCTVER)"
+		read -p "Do you still want to continue? [y/N] " SKIP_INCORRECT_SAMPLE_FIRMWARE_VERSION_RULE
+		if [ "$SKIP_INCORRECT_SAMPLE_FIRMWARE_VERSION_RULE" != "y" ] && [ "$SKIP_INCORRECT_SAMPLE_FIRMWARE_VERSION_RULE" != "Y" ] ; then
+			exit 1
+		fi
+	fi
+
 fi
 
 # prepare to copy firmware to remote
