Make Hathor compatible with onefw project (version 1.0.3.0)
#############################
# Original project
#############################
- No need to source devel file in firmware_tag_create
- When first release the project (ie. version is 0100a), hathor put history.txt directly and no need to backup history.txt

##############################
# Onefw project
##############################
- Onefw offers the revision freezing mechanism, so there is no need to make a svn tag.
- Use the other script 'svnst' instead of 'svn st'
- Add env variable $DEVELFILE to indicate devel file
  (ex: DEVELFILE=devel_hisillicon_standard)
- During build_kernel/build_firmware, each of them would source devel file.
  Besides that, firmware_prerelease would source devel file too.
  Avoid sourcing too much time, we cache the major environment variable and source it if necessary 
- Improve the bug_report.py to fetch bug info from redmine and svn log
- add new python code to generate support_list.xls
- Where to put FW and history.txt on Athena?
  please refer to http://rd1-1/rd1wiki/index.php/One_FW%E9%80%B2%E6%B8%AC%E6%B5%81%E7%A8%8B

git-svn-id: http://rd1-1/subversion/SI/Tools/hathor/trunk@176840 7a6c5977-b700-0410-9ebf-f0490b269a9c

diff --git a/bin/firmware_copy b/bin/firmware_copy
--- a/bin/firmware_copy
+++ b/bin/firmware_copy
@@ -3,11 +3,16 @@
 source $HATHOR/config/basic_config
 source $HATHOR/lib/libfirmwareinfo
 source $HATHOR/lib/libmessage
+source $HATHOR/lib/libsmb
+#set -x
 
 hathor_get_firmware_path
 
-
-DIRECTORY_TO_PUT_FIRMWARE=$FIRMWARE_VERSION
+if [ "$ISONEFW" == "true" ]; then
+    DIRECTORY_TO_PUT_FIRMWARE=$PRODUCTVER
+else
+	DIRECTORY_TO_PUT_FIRMWARE=$FIRMWARE_VERSION
+fi
 
 FIRMWARE_TO_UPLOAD="`ls $RELEASE_DIR/$PRODUCTVER* $RELEASE_DIR/sd.rom $RELEASE_DIR/sdboot*`"
 for f in $FIRMWARE_TO_UPLOAD; do
@@ -19,10 +24,31 @@ SMB_CMD_FIRMWARE="mkdir $DIRECTORY_TO_PUT_FIRMWARE; cd $DIRECTORY_TO_PUT_FIRMWAR
 
 
 RETRY_COUNT=2
+check_identity=0
 info "準備將 firmware 和 history.txt 上傳至雅典娜"
 warn "密碼錯誤重試次數只有 $RETRY_COUNT 次，請小心輸入"
-read -s -p "密碼: " PASSWORD
-echo 
+for i in `seq 1 $RETRY_COUNT`; do
+    read -s -p "密碼: " PASSWORD
+    echo 
+    hathor_check_dir_exists $FIRMWARE_PATH_SERVER_REVERTED $HATHOR_FIRMWARE_PATH_PREFIX_REVERTED $USERNAME_ATHENA $PASSWORD
+    if [ "$?" == "0" ]; then
+        check_identity=1
+        break
+    else
+        if [ "$ret" == "NT_STATUS_LOGON_FAILURE" ]; then
+            warn '密碼錯誤!!'
+            warn "重試次數還有 `expr $RETRY_COUNT - $i` 次，請小心輸入"
+        else
+            warn "Error: $ret"
+            break
+        fi
+    fi
+done
+
+if [ "$check_identity" == "0" ] ; then
+    warn "密碼錯誤!"
+    exit 1
+fi
 
 export USER=$USERNAME_ATHENA
 export PASSWD=$PASSWORD
@@ -35,16 +61,40 @@ fi
 
 ###  upload history.txt
 
-# get correct history path first
-hathor_get_history_path $FIRMWARE_PATH_SERVER_REVERTED $HATHOR_FIRMWARE_PATH_PREFIX_REVERTED $USERNAME_ATHENA $PASSWORD
+if [ "$ISONEFW" == "true" ]; then
+	HATHOR_FIRMWARE_HISTORY_FOLDER="$HATHOR_FIRMWARE_PATH_PREFIX_REVERTED/$PRODUCTVER"
+	SMB_CMD_HISTORY="put $RELEASE_DIR/history.txt history.txt"
+else
+	# get correct history path first
+	hathor_get_history_path $FIRMWARE_PATH_SERVER_REVERTED $HATHOR_FIRMWARE_PATH_PREFIX_REVERTED $USERNAME_ATHENA $PASSWORD
 
-export USER=$USERNAME_ATHENA
-export PASSWD=$PASSWORD
-SMB_CMD_HISTORY="get $HATHOR_FIRMWARE_HISTORY_NAME $HATHOR_FIRMWARE_HISTORY_NAME.bak; put $RELEASE_DIR/history.txt $HATHOR_FIRMWARE_HISTORY_NAME; put $HATHOR_FIRMWARE_HISTORY_NAME.bak"
+	export USER=$USERNAME_ATHENA
+	export PASSWD=$PASSWORD
+
+	if [ -z "$HATHOR_FIRMWARE_HISTORY_NAME" ]; then
+		# first release to Athena
+		SMB_CMD_HISTORY="put $RELEASE_DIR/history.txt history.txt"
+	else
+		SMB_CMD_HISTORY="get $HATHOR_FIRMWARE_HISTORY_NAME $HATHOR_FIRMWARE_HISTORY_NAME.bak; put $RELEASE_DIR/history.txt $HATHOR_FIRMWARE_HISTORY_NAME; put $HATHOR_FIRMWARE_HISTORY_NAME.bak"
+	fi
+fi
 ret=`SMB_Command "$FIRMWARE_PATH_SERVER_REVERTED" "$HATHOR_FIRMWARE_HISTORY_FOLDER" "$SMB_CMD_HISTORY"`
 if [ "$ret" != "" ]; then
-	warn "檔案上傳失敗! ($ret)"
+	warn "history.txt上傳失敗! ($ret)"
 	exit 1
 fi
 
+### upload image_library_release_note.log
+if [ "$ISONEFW" == "true" ]; then
+	HATHOR_FIRMWARE_IMAGELIBLOG_FOLDER="$HATHOR_FIRMWARE_PATH_PREFIX_REVERTED"
+	SMB_CMD_FILES="put $RELEASE_DIR/image_library_release_note.log image_library_release_note.log; put $RELEASE_DIR/support_list.xls support_list.xls"
+
+	ret=`SMB_Command "$FIRMWARE_PATH_SERVER_REVERTED" "$HATHOR_FIRMWARE_IMAGELIBLOG_FOLDER" "$SMB_CMD_FILES"`
+	if [ "$ret" != "" ]; then
+		warn "image lib release note 和 support_list.xml 上傳失敗! ($ret)"
+		exit 1
+	fi
+fi
+
+info "上傳成功!"
 unset PASSWD; unset USER
diff --git a/bin/firmware_prerelease b/bin/firmware_prerelease
--- a/bin/firmware_prerelease
+++ b/bin/firmware_prerelease
@@ -2,6 +2,7 @@
 
 source $HATHOR/config/basic_config
 source $HATHOR/lib/libfirmwarerelease
+source $HATHOR/lib/libmessage
 
 set +o posix
 TEMP_PRODUCT_DIR="$TEMP_DIR/$PRODUCTVER"
@@ -14,8 +15,32 @@ else
 	echo "$0: Where to find apps_config.config?"
 	exit 1
 fi
+
+
 cd $TEMP_PRODUCT_DIR/build/
-source $DEVEL_SOURCE_FILE
+
+#if [ "$ISONEFW" == "true" ]; then
+    #if [ -n "$SHARE_BASE" ]; then
+		#DEVEL_SOURCE_FILE=$DEVELFILE 	
+	#else
+		#DEVEL_SOURCE_FILE="devel_${PRODUCTNAME,,}"
+	#fi
+#else
+	#DEVEL_SOURCE_FILE="devel_`echo $PRODUCTVER | sed -e 's/-[^-]*$//' -e 's/-/_/g'`"
+#fi
+
+#info "\nHathor would source $DEVEL_SOURCE_FILE more then one time."
+#info "Choose the same build version if needed"
+#source $DEVEL_SOURCE_FILE
+
+source $HOME/.hathor/sourceme
+
+if [ -f $FIRMWARE_CONFIG ] ; then 
+	source $FIRMWARE_CONFIG
+else
+	warn "$FIRMWARE_CONFIG not found, quit!"
+	exit 1;
+fi
 
 # create product dir if it doesn't exist
 [ -d "$RELEASE_DIR" ] || mkdir $RELEASE_DIR
@@ -25,6 +50,12 @@ copy_firmware
 echo "Firmware copied (${PRODUCTVER})."
 
 copy_history
+
+if [ "$ISONEFW" == "true" ]; then
+	copy_image_lib_release_note
+	copy_supportlist
+	info "support_list.xls 已產生至  $RELEASE_DIR/support_list.xls"
+fi
 
 # copy rootfs/flashfs log
 copy_filesystem_log
diff --git a/bin/gen_history b/bin/gen_history
--- a/bin/gen_history
+++ b/bin/gen_history
@@ -4,10 +4,15 @@ source $HATHOR/config/basic_config
 source $HATHOR/lib/libfirmwareinfo
 source $HATHOR/lib/libmessage
 
+# Get the $PRODUCTVER from cache
+# this value would be the file name of history-$PRODUCTVER.txt 
+HATHOR_PRODUCTVER=`cat ~/.hathor/sourceme | grep "PRODUCTVER" | awk -F'=' '{print $2}' | sed s/\"//g`
+[ -z $HATHOR_PRODUCTVER ] && HATHOR_PRODUCTVER=$PRODUCTVER
+
 # This script is used for generate history.txt file
 FILEPP="filepp -e -I$OUTPUT_DIR"
 HISTORY_TEMPLATE="history.txt.pp"
-HISTORY_THIS_TIME="$OUTPUT_DIR/history-$PRODUCTVER.txt"
+HISTORY_THIS_TIME="$OUTPUT_DIR/history-$HATHOR_PRODUCTVER.txt"
 
 # generate firmware connfig 
 $HATHOR/bin/gen_firmware_config
@@ -19,6 +24,30 @@ else
 	exit 1;
 fi
 
+PARENT_PKG_PATH="$OUTPUT_DIR/parent_pkg"
+if [ "$ISONEFW" == "true" ]; then
+	if [ -f "$PARENT_PKG_PATH" ]; then
+		echo "Previous release pkg version is `cat $PARENT_PKG_PATH`"
+	else
+		info "The current release pkg version is $PRODUCTVER"
+		info "What is the 'last' release pkg version ?"
+		read -p "" PKG 
+		echo $PKG > $PARENT_PKG_PATH
+		info "\nHathor would generate pkg tree automatically, but we need the information."
+		info "Is current release pkg (a)still in the trunk (b)in another new branch ?"
+		read -p "" TRUNK 
+		if [ "$TRUNK" == "b" ]; then
+			echo "branch" >> $PARENT_PKG_PATH
+		else
+			echo "trunk" >> $PARENT_PKG_PATH
+		fi
+	fi        
+
+	export PARENT_PKG=`cat $PARENT_PKG_PATH | head -n 1`
+
+fi
+
+info "\n準備從 redmine 和 svn log 抓取 bug fixing information" 
 # gathering fixed bugs from bugzilla
 $EXEC/get_fixed_bugs
 if [ "$?" != "0" ] ; then
@@ -28,21 +57,36 @@ fi
 
 # gathering history related stuff from athena
 $EXEC/get_previous_firmware_history
-if [ "$?" != "0" ]; then
-	if [ "$FIRMWARE_VERSION" == "0100a" ]; then
-		info "看來你是第一次 release $PRODUCTVER，所以找不到 history.txt 也是很正常的。"
-		touch $HISTORY_ATHENA
+ret="$?"
+if [ "$ret" != "0" ]; then
+	if [ "$ISONEFW" == "true" ];then
+		if [ "$ret" == 2 ]; then
+			exit 1
+		else
+			info "是第一次 release 這個平台的 pkg 嗎? [y/N]"
+			read -p "" FIRST 
+			if [ "$FIRST" != "y" ] && [ "$FIRST" != "Y" ] ; then
+				warn "請確認前一版 pkg 是否存在 athena 上"
+				exit 1
+			fi
+			touch $HISTORY_ATHENA
+		fi
 	else
-		warn "Get previous firmware history error, quit"
-		exit 1
+		if [ "$FIRMWARE_VERSION" == "0100a" ]; then
+			info "看來你是第一次 release $PRODUCTVER，所以找不到 history.txt 也是很正常的。"
+			touch $HISTORY_ATHENA
+		else
+			warn "Get previous firmware history error, quit"
+			exit 1
+		fi
 	fi
 fi
 
 # gathering module versions, we will filter out stuff that we don't care (such as open source programs)
 RunCommandWithSpinningIndicator "$EXEC/gen_module_versions" "產生模組版本資訊"
 if [ "$?" != "0" ]; then
-	warn "Get module versions error, quit"
-	exit 1
+    warn "Get module versions error, quit"
+    exit 1
 fi
 
 # all done, generate history.txt
@@ -69,4 +113,4 @@ cp $HISTORY_ATHENA $RELEASE_DIR
 unix2dos $HISTORY_THIS_TIME 
 cp $HISTORY_THIS_TIME $RELEASE_DIR
 
-info "history.txt 已產生至 $RELEASE_DIR/history-$PRODUCTVER.txt"
+info "history.txt 已產生至 $RELEASE_DIR/history-$HATHOR_PRODUCTVER.txt"
diff --git a/bin/get_fixed_bugs b/bin/get_fixed_bugs
--- a/bin/get_fixed_bugs
+++ b/bin/get_fixed_bugs
@@ -9,22 +9,22 @@ BASE="http://dqa01.vivotek.tw/bugzilla/"
 BUGZ="bugz -q --columns 1024"
 BRAND=`echo $PRODUCTVER | awk -F- '{print $2}'`
 
-echo "Get bug list from redmine (http://dqa02.vivotek.tw/redmine/)..."
+#echo "Get bug list from redmine (http://dqa02.vivotek.tw/redmine/)..."
 
-$HATHOR/bin/bug_report.py $OUTPUT
+$HATHOR/bin/bug_report_improve.py $OUTPUT
 
-echo "Get bug list from bugzilla ($BASE)..."
+#echo "Get bug list from bugzilla ($BASE)..."
 
 [ -f $CONFIG ] && source $CONFIG
 
-MODEL="$BRAND $PRODUCTNAME"
+#MODEL="$BRAND $PRODUCTNAME"
 
-$BUGZ -b $BASE search --product "$MODEL" --status 'RESOLVED' --resolution 'fixed' | tee -a $OUTPUT
-bugz_result=$?
-if [ "$bugz_result" -ne "0" ] ; then
-	warn "Unable to retrieve bug list from bugzilla"
-	exit 1
-fi
+#$BUGZ -b $BASE search --product "$MODEL" --status 'RESOLVED' --resolution 'fixed' | tee -a $OUTPUT
+#bugz_result=$?
+#if [ "$bugz_result" -ne "0" ] ; then
+	#warn "Unable to retrieve bug list from bugzilla"
+	#exit 1
+#fi
 
 # Generate "<None>" if no fixed bug found in this release
 OUTPUT_FILESIZE=`stat -c "%s" $OUTPUT`
