stash stuff here
git-svn-id: http://rd1-1/subversion/SI/Tools/hathor/trunk@139427 7a6c5977-b700-0410-9ebf-f0490b269a9c

diff --git a/bin/gen_history b/bin/gen_history
--- a/bin/gen_history
+++ b/bin/gen_history
@@ -29,8 +29,13 @@ fi
 # gathering history related stuff from athena
 $EXEC/get_previous_firmware_history
 if [ "$?" != "0" ]; then
-	warn "Get previous firmware history error, quit"
-	exit 1
+	if [ "$FIRMWARE_VERSION" == "0100a" ]; then
+		info "看來你是第一次 release $PRODUCTVER，所以找不到 history.txt 也是很正常的。"
+		touch history.txt
+	else
+		warn "Get previous firmware history error, quit"
+		exit 1
+	fi
 fi
 
 # gathering module versions, we will filter out stuff that we don't care (such as open source programs)
diff --git a/bin/get_previous_firmware_history b/bin/get_previous_firmware_history
--- a/bin/get_previous_firmware_history
+++ b/bin/get_previous_firmware_history
@@ -5,7 +5,12 @@ source $HATHOR/lib/libfirmwareinfo
 source $HATHOR/lib/libmessage
 source $HATHOR/lib/libsmb
 
+FIRST_RELEASE=0
 RETRY_COUNT=2
+
+if [ `echo "$FIRMWARE_VERSION" | awk '{print $3}'` == "0100a" ]; then
+	FIRST_RELEASE=1
+fi
 
 [ -f "$FIRMWARE_CONFIG" ] && source $FIRMWARE_CONFIG
 hathor_get_firmware_path
@@ -19,18 +24,23 @@ for i in `seq 1 $RETRY_COUNT`; do
 	read -s -p "密碼: " PASSWORD_ATHENA
 	echo
 	info "連線中..."
-	hathor_get_history_path $FIRMWARE_PATH_SERVER_REVERTED $HATHOR_FIRMWARE_PATH_PREFIX_REVERTED $USERNAME_ATHENA $PASSWORD_ATHENA
-	if [ "$?" == "0" ] ; then
+	ret=`hathor_get_history_path $FIRMWARE_PATH_SERVER_REVERTED $HATHOR_FIRMWARE_PATH_PREFIX_REVERTED $USERNAME_ATHENA $PASSWORD_ATHENA`
+	if [ "$?" == "0" ]; then
 		get_history_success=1
 		break;
 	else 
-		warn '連線失敗!!'
-		warn "重試次數還有 `expr $RETRY_COUNT - $i` 次，請小心輸入"
+		if [ "$ret" == "NT_STATUS_LOGON_FAILURE" ]; then
+			warn '連線失敗!!'
+			warn "重試次數還有 `expr $RETRY_COUNT - $i` 次，請小心輸入"
+		else
+			warn "Error: $ret"
+			break
+		fi
 	fi
 done
 
 if [ "$get_history_success" == "0" ] ; then
-	warn "與 Athena 連線失敗!"
+	warn "偵測 firmware 目錄失敗"
 	exit 1
 fi
 
diff --git a/lib/libsmb b/lib/libsmb
--- a/lib/libsmb
+++ b/lib/libsmb
@@ -8,7 +8,7 @@ function SMB_Command
 
 	# do not login if USER/PASSWD is not set
 	if [ -z "$USER" ] || [ -z "$PASSWD" ] ; then 
-		echo "NT_STATUS_OBJECT_LOGON_FAILURE"
+		echo "NT_STATUS_LOGON_FAILURE"
 		return 1
 	fi
 
@@ -32,6 +32,7 @@ function SMB_CheckIfDirectoryExists
 
 	ret=`SMB_Command $server $directory 'exit'`
 	if [ "$ret" == "NT_STATUS_OBJECT_PATH_NOT_FOUND" ] ; then
+		warn "$directory 找不到!" 1>&2
 		echo 'false'
 		return 1
 	elif [ "$ret" != "" ] ; then
