add check for command return (quit on execution fail), check correct plug-in version location
git-svn-id: http://rd1-1/subversion/SI/Tools/hathor/trunk@110718 7a6c5977-b700-0410-9ebf-f0490b269a9c

diff --git a/src/bin/gen_history b/src/bin/gen_history
--- a/src/bin/gen_history
+++ b/src/bin/gen_history
@@ -20,16 +20,32 @@ fi
 
 # gathering fixed bugs from bugzilla
 $EXEC/get_fixed_bugs
+if [ "$?" != "0" ] ; then
+	echo "Get fixed bugs error, quit"
+	exit 1
+fi
 
 # gathering history related stuff from athena
 $EXEC/get_previous_firmware_history
+if [ "$?" != "0" ]; then
+	echo "Get previous firmware history error, quit"
+	exit 1
+fi
 
 # gathering module versions, we will filter out stuff that we don't care (such as open source programs)
 $EXEC/gen_module_versions
+if [ "$?" != "0" ]; then
+	echo "Get module versions error, quit"
+	exit 1
+fi
 
 # all done, generate history.txt
 echo 'Generating history.txt...'
 $FILEPP $HATHOR/template/$HISTORY_TEMPLATE -o $HISTORY_THIS_TIME
+if [ "$?" != "0" ]; then
+	echo "Generate history.txt failed, quit"
+	exit 1
+fi
 
 encoding_of_previous_history=`file $HISTORY_ATHENA | grep "UTF-8"`
 if [ -z "$encoding_of_previous_history" ] ; then
diff --git a/src/bin/get_fixed_bugs b/src/bin/get_fixed_bugs
--- a/src/bin/get_fixed_bugs
+++ b/src/bin/get_fixed_bugs
@@ -15,6 +15,11 @@ echo "Get bug list from bugzilla ($BASE)..."
 MODEL="$BRAND $PRODUCTNAME"
 
 $BUGZ -b $BASE search --product "$MODEL" --status 'RESOLVED' --resolution 'fixed' > $OUTPUT
+bugz_result=$?
+if [ "$bugz_result" -ne "0" ] ; then
+	echo "Unable to retrieve bug list from bugzilla"
+	exit 1
+fi
 
 # Generate "<None>" if no fixed bug found in this release
 OUTPUT_FILESIZE=`stat -c "%s" $OUTPUT`
