sync
git-svn-id: http://rd1-1/subversion/SI/Tools/hathor/trunk@110405 7a6c5977-b700-0410-9ebf-f0490b269a9c

diff --git a/src/bin/get_previous_firmware_history b/src/bin/get_previous_firmware_history
--- a/src/bin/get_previous_firmware_history
+++ b/src/bin/get_previous_firmware_history
@@ -12,7 +12,15 @@ HATHOR_FIRMWARE_PATH_PREFIX_REVERTED=`echo $HATHOR_FIRMWARE_PATH_PREFIX | sed -e
 [ -f "$HISTORY_ATHENA" ] && rm -f "$HISTORY_ATHENA"
 
 echo "Get previous history.txt from Athena, please input athena password:"
-smbclient "$FIRMWARE_PATH_SERVER_REVERTED" -U klaymen.chang -D "$HATHOR_FIRMWARE_PATH_PREFIX_REVERTED" -c "get history.txt" 2> /dev/null
+for i in `seq 1 3`; do
+	smbclient "$FIRMWARE_PATH_SERVER_REVERTED" -U klaymen.chang -D "$HATHOR_FIRMWARE_PATH_PREFIX_REVERTED" -c "get history.txt" 2> /dev/null
+	smbclient_result=$?
+	if [ "$?" = "0" ]; then
+		# smbclient connect success
+		break
+	fi
+	echo "Unable to retrieve history.txt from athena, retry"
+done
 dos2unix history.txt 2> /dev/null
 mv history.txt $HISTORY_ATHENA
 
