sync
git-svn-id: http://rd1-1/subversion/SI/Tools/hathor/trunk@110422 7a6c5977-b700-0410-9ebf-f0490b269a9c

diff --git a/src/bin/get_previous_firmware_history b/src/bin/get_previous_firmware_history
--- a/src/bin/get_previous_firmware_history
+++ b/src/bin/get_previous_firmware_history
@@ -3,7 +3,11 @@
 source $HATHOR/config/basic_config
 source $HATHOR/lib/libfirmwareinfo
 
-[ -f "$FIRMWARE_CONFIG" ] || exit
+if [ -f "$FIRMWARE_CONFIG" ]; then
+	echo "Firmware config ($FIRMWARE_CONFIG) not found"
+	exit 1
+fi
+
 source $FIRMWARE_CONFIG
 hathor_get_firmware_path
 
